Update CI

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -707,28 +707,52 @@ jobs:
           cache-dependency-path: complement/go.sum
           go-version-file: complement/go.mod
 
-      # - name: Run Complement Tests
-      #   id: run_complement_tests
-      #   # -p=1: We're using `-p 1` to force the test packages to run serially as GHA boxes
-      #   #     are underpowered and don't like running tons of Synapse instances at once.
-      #   # -json: Output JSON format so that gotestfmt can parse it.
-      #   #
-      #   # tee /tmp/gotest-complement.log: We tee the output to a file so that we can re-process it
-      #   # later on for better formatting with gotestfmt. But we still want the command
-      #   # to output to the terminal as it runs so we can see what's happening in
-      #   # real-time.
-      #   run: |
-      #     set -o pipefail
-      #     COMPLEMENT_DIR=`pwd`/complement synapse/scripts-dev/complement.sh -p 1 -json 2>&1 | tee /tmp/gotest-complement.log
-      #   shell: bash
-      #   env:
-      #     POSTGRES: ${{ (matrix.database == 'Postgres') && 1 || '' }}
-      #     WORKERS: ${{ (matrix.arrangement == 'workers') && 1 || '' }}
+      # Run the image sanity check test first as this is the first thing we want to know
+      # about (are we actually testing what we expect?) and we don't want to debug
+      # downstream failures (wild goose chase).
+      - name: Sanity check Complement image
+        id: run_sanity_check_complement_image_test
+        # -p=1: We're using `-p 1` to force the test packages to run serially as GHA boxes
+        #     are underpowered and don't like running tons of Synapse instances at once.
+        # -json: Output JSON format so that gotestfmt can parse it.
+        #
+        # tee /tmp/gotest-complement.log: We tee the output to a file so that we can re-process it
+        # later on for better formatting with gotestfmt. But we still want the command
+        # to output to the terminal as it runs so we can see what's happening in
+        # real-time.
+        run: |
+          set -o pipefail
+          COMPLEMENT_DIR=`pwd`/complement synapse/scripts-dev/complement.sh -p 1 -json -run 'TestSynapseVersion/Synapse_version_matches_current_git_checkout' 2>&1 | tee /tmp/gotest-complement.log
+        shell: bash
+        env:
+          POSTGRES: ${{ (matrix.database == 'Postgres') && 1 || '' }}
+          WORKERS: ${{ (matrix.arrangement == 'workers') && 1 || '' }}
+        # We don't run `gotestfmt` for the sanity check step as it's only one test so
+        # there is nothing to organize. And the extra step is more noise to click
+        # through and grok. If this step fails, it will be obvious still.
 
-      # - name: Formatted Complement test logs
-      #   # Always run this step if we attempted to run the Complement tests.
-      #   if: always() && steps.run_complement_tests.outcome != 'skipped'
-      #   run: cat /tmp/gotest-complement.log | gotestfmt -hide "successful-downloads,empty-packages"
+      - name: Run Complement Tests
+        id: run_complement_tests
+        # -p=1: We're using `-p 1` to force the test packages to run serially as GHA boxes
+        #     are underpowered and don't like running tons of Synapse instances at once.
+        # -json: Output JSON format so that gotestfmt can parse it.
+        #
+        # tee /tmp/gotest-complement.log: We tee the output to a file so that we can re-process it
+        # later on for better formatting with gotestfmt. But we still want the command
+        # to output to the terminal as it runs so we can see what's happening in
+        # real-time.
+        run: |
+          set -o pipefail
+          COMPLEMENT_DIR=`pwd`/complement synapse/scripts-dev/complement.sh -p 1 -json 2>&1 | tee /tmp/gotest-complement.log
+        shell: bash
+        env:
+          POSTGRES: ${{ (matrix.database == 'Postgres') && 1 || '' }}
+          WORKERS: ${{ (matrix.arrangement == 'workers') && 1 || '' }}
+
+      - name: Formatted Complement test logs
+        # Always run this step if we attempted to run the Complement tests.
+        if: always() && steps.run_complement_tests.outcome != 'skipped'
+        run: cat /tmp/gotest-complement.log | gotestfmt -hide "successful-downloads,empty-packages"
 
       - name: Run in-repo Complement Tests
         id: run_in_repo_complement_tests
